### PR TITLE
Difference between state and event

### PR DESCRIPTION
**Pull request by vitorsouzaalmeida**
PR to write about State in ReactJS

### CODE REVIEW

**Review by biantris — APPROVED** [review]
Good example 🚀

**Comment by vitorsouzaalmeida** [comment]
Now I need to fix some issues with typos and run this text in Grammarly

**Comment by vitorsouzaalmeida** [comment]
And maybe start the translation? I don't know yet. But I need to translate

**Comment by vitorsouzaalmeida** [comment]
I'm only pasting the translation... Is not the final yet. I don't like to translate technical terms, so I'll review and maintain the "state" instead "estados" for example.

**Comment by vitorsouzaalmeida** [comment]
I think is done.
Now I need to fix some typos, review them with Grammarly and ask for feedback.

**Review by scarletquasar — APPROVED** [review]

**Pull request merged**
